# Generated by Django 4.2.2 on 2023-08-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='userName',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
